import type { Metadata } from 'next'
import './globals.css'
import Nav from '@/components/nav'
import { Kanit } from 'next/font/google'

const inter = Kanit({ weight: "500", subsets: ['latin']});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[var(--background)] text-[var(--base)]`}>
				<Nav />
				{children}
			</body>
		</html>
	)
}
