import type { Metadata } from "next";
import "./globals.css";


import { Analytics } from '@vercel/analytics/react';


export const metadata: Metadata = {
  title: "Poly Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={``}>
          <div>{children}</div>
		  <Analytics />
      </body>
    </html>
  );
}
